name: "nix builder"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: trickypr
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: "true"
    - run: nix build .
      # only push up the unwrapped binaries
    - run: nix build .#unwrapped --json | jq -r '.[].outputs' | to_entries[].value | cachix push trickypr
